config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :user_favorite_batches, only: [:index]
  resources :items, only: [:new, :create, :index, :destroy, :edit, :update]
  resources :item_categories, only: [:new, :create, :edit, :update]
  resources :batches, only: [:new, :create, :show, :index] do
    get 'search', on: :collection
    get 'admin', on: :member, to: 'batches#show_admin', as: 'show_admin'
    get 'in_progress', on: :collection
    get 'future', on: :collection
    resources :bids, only: [:create, :new]
    resources :doubts, only: [:create, :new] do
      resources :answers, only: [:create, :new]
    end
    get 'expired', on: :collection
    get 'batches_with_my_bids', on: :collection
    patch 'cancel', on: :member
    patch 'close', on: :member
  end
  resources :batch_items, only: [:create]
  patch 'doubts/:id/set_answered', to: 'doubts#set_answered', as: 'set_doubt_answered'
  get 'doubts/not_answered', to: 'doubts#not_answered'
  get 'doubts/:id/checked_answered_adm_button', to: 'doubts#answered_checked', as: 'answered_button_checked'
  get 'doubts/:id/unchecked_answered_adm_button', to: 'doubts#answered_unchecked', as: 'answered_button_unchecked'
  get 'doubts/:id/visible', to: 'doubts#visible', as: 'doubts_visible'
  get 'doubts/:id/not_visible', to: 'doubts#not_visible', as: 'doubts_not_visible'
  get 'doubts/:id/name_not_ocult', to: 'doubts#name_not_ocult', as: 'doubts_name_not_ocult'
  get 'doubts/:id/name_ocult', to: 'doubts#name_ocult', as: 'doubts_name_ocult'
  delete 'user_favorite_batches/delete_favorited/:id', to: 'user_favorite_batches#delete_favorited', as: 'user_favorited_batches_delete_favorited'
  post 'user_favorite_batches/:user_id/:batch_id', to: 'user_favorite_batches#create', as: 'create_user_favorite_batch'
  patch 'doubts/:id/set_visibility', to: 'doubts#set_visiblity', as: 'set_doubt_visibility'
  delete 'batch_items', to: 'batch_items#delete_many'
  patch 'batches/:batch_id/approve/:user_id', to: 'batches#approve', as: 'approve_batch'
  get 'users/block_and_unblock_page', to: 'users#block_and_unblock_page', as: 'block_and_unblock_cpf_page'
  get 'users/:id', to: 'users#profile', as: 'users_profile'
  patch '/users/:id/block_and_unblock_cpf', to: 'users#block_and_unblock', as: 'block_user_cpf'
  patch '/users(/:cpf)/block_and_unblock_cpf_in_page', to: 'users#block_and_unblock_cpf_in_page', as: 'block_user_cpf_in_page'
end

app/models/doubt.rb
class Doubt < ApplicationRecord
  include ActiveModel::Dirty
  belongs_to :user
  belongs_to :batch
  has_many :answers
  validates :content, presence: true
  after_create_commit :handle_broadcasting_create
  after_update_commit :handle_broadcasting_update

  scope :visible, -> { where(visible: true) }
  scope :answered, -> { where(answered: true) }
  scope :not_answered, -> { where(answered: false) }
  

  def handle_broadcasting_create
    if self.batch.doubts.not_answered.count == 1
      broadcast_remove_to "not_answered", target: 'no_doubts_open'
    end
    if self.batch.doubts.count == 1
      broadcast_remove_to "batch", target: 'no_doubts'
      broadcast_remove_to "batch_admin", target: 'no_doubts'
    end
      broadcast_append_to "batch"
      broadcast_append_to "not_answered", target: 'not_answereds', partial: 'doubts/doubt_adm'
      broadcast_append_to "batch_admin", partial: 'doubts/doubt_adm'
  end

  def handle_broadcasting_update
    if previous_changes.include?(:answered)
      if answered == true
        broadcast_replace_to "not_answered", target: "toggle_answered_button_#{id}", partial: 'doubts/answered_checked', locals: {id: id}
        broadcast_replace_to "batch_admin", target: "toggle_answered_button_#{id}", partial: 'doubts/answered_checked', locals: {id: id}
      else
        broadcast_replace_to "not_answered", target: "toggle_answered_button_#{id}", partial: 'doubts/answered_unchecked', locals: {id: id}
        broadcast_replace_to "batch_admin", target: "toggle_answered_button_#{id}", partial: 'doubts/answered_unchecked', locals: {id: id}
      end
    end
    if previous_changes.include?(:visible)
      if visible == true
        broadcast_replace_to "batch_admin", target: "name_ocult_toggle_#{id}", partial: 'doubts/name_not_ocult', locals: {id: id}
        broadcast_replace_to "not_answered", target: "name_ocult_toggle_#{id}", partial: 'doubts/name_not_ocult', locals: {id: id}
        if Doubt.all.visible.count == 1
          broadcast_remove_to 'batch', target: 'no_doubts'
        end
        broadcast_append_to 'batch'
        broadcast_replace_to "not_answered", target: "toggle_visibility_button_#{id}", partial: 'doubts/visible', locals: {id: id}
        broadcast_replace_to "batch_admin", target: "toggle_visibility_button_#{id}", partial: 'doubts/visible', locals: {id: id}
      else
        broadcast_replace_to "batch_admin", target: "name_ocult_toggle_#{id}", partial: 'doubts/name_ocult', locals: {id: id}
        broadcast_replace_to "not_answered", target: "name_ocult_toggle_#{id}", partial: 'doubts/name_ocult', locals: {id: id}
        broadcast_remove_to "batch", target: "doubt_#{id}"
        if Doubt.all.visible.count == 0
          broadcast_append_to "batch", partial: 'doubts/no_doubts'
        end
        broadcast_replace_to "not_answered", target: "toggle_visibility_button_#{id}", partial: 'doubts/not_visible', locals: {id: id}
        broadcast_replace_to "batch_admin", target: "toggle_visibility_button_#{id}", partial: 'doubts/not_visible', locals: {id: id}
      end
    end
  end
end

app/controllers/doubts_controller.rb
class DoubtsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user_with_blocked_cpf!, only: [:create]
  before_action :authenticate_admin!, only: [:not_answered, :set_answered, :set_visibility]

  def new
    @batch = Batch.find(params[:batch_id])
    @doubt = @batch.doubts.new
  end

  def create
    @doubt = Doubt.new(doubt_params)

    if current_user.id != @doubt.user_id
      respond_to do |format|
        format.turbo_stream
        format.html { render :error_page, status: :unprocessable_entity }
      end
      return
    end

    approved_by = @doubt.batch.approved_by
    start_date = @doubt.batch.start_date
    end_date = @doubt.batch.end_date
    bids_present = @doubt.batch.bids.present?
    maximum_bid_amount = @doubt.batch.bids.maximum(:amount)

    if (approved_by && Date.today < end_date && Date.today >= start_date) ||
       (approved_by && Date.today >= end_date && bids_present && @doubt.batch.bids.find_by(amount: maximum_bid_amount).user_id == current_user.id)
      if @doubt.save
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace("error-messages-doubt", partial: "shared/error_messages", locals: { resource: @doubt }) }
          format.html { redirect_to @doubt.batch }
        end
        return
      else
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace("error-messages-doubt", partial: "shared/error_messages", locals: { resource: @doubt }) }
          format.html { render :new, status: :unprocessable_entity }
        end
        return
      end
    end
    respond_to do |format|
      format.turbo_stream
      format.html { render :error_page, status: :unprocessable_entity }
    end
  end

  def not_answered
    @doubts = Doubt.all.where(answered: false)
  end

  def name_ocult
    @doubt = Doubt.find(params[:id])
  end

  def name_not_ocult
    @doubt = Doubt.find(params[:id])
  end
  
  def answered_checked
    @id = params[:id]
  end

  def answered_unchecked
    @id = params[:id]
  end

  def visible
    @id = params[:id]
  end

  def not_visible
    @id = params[:id]
  end
  

  def doubt_params
    params.require(:doubt).permit(:content, :batch_id, :user_id)
  end

  def set_answered
    doubt = Doubt.find(params[:id])
    if doubt.answered == true
      doubt.answered = false
    else
      doubt.answered = true
    end
    doubt.save!
  end

  def set_visiblity
    doubt = Doubt.find(params[:id])
    if doubt.visible == true
      doubt.visible = false
    else
      doubt.visible = true
    end
    doubt.save!
  end

  private 
  
  def authenticate_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: 'Você não tem permissão para acessar essa página.'
    end
  end

  def authenticate_user_with_blocked_cpf!
    authenticate_user!

    if current_user.blocked_cpf_id.present?
      redirect_to root_path, alert: 'Sua conta está suspensa'
    end
  end
end

app/views/doubts/_answered_checked.html.erb
 <%= turbo_frame_tag "toggle_answered_button_#{id}", src: answered_button_checked_path(id) %>

app/views/doubts/_doubt.html.erb
<div id="<%= dom_id doubt %>">
  <h4><%= doubt.user.name %>
    <% if doubt.user.admin %>
      (Administrador)
    <% end %>
  </h4>
  <p><%= doubt.content %></p>
  <div data-controller="answers">
    <button data-action="click->answers#toggleSection">Respostas</button>
    <section id="answers_<%= doubt.id %>", data-answers-target="section", class="hidden">
      <%= render doubt.answers %>
      <% if doubt.answers.empty? %>
        <p id="no_answers_<%=doubt.id%>">Ainda não existem respostas para essa dúvida</p>
      <% end %>
    </section>
    <div class="hidden", data-answers-target="new_answer_form">
    <div id="error-messages-answer_<%=doubt.id%>"></div>
    <% if Current.user %>
      <%= turbo_frame_tag "new_answer_#{doubt.id}", src: new_batch_doubt_answer_path(doubt.batch.id, doubt.id), target: "new_answer_#{doubt.id}" %>
    <% end %>
    </div>
  </div>
</div>

app/views/doubts/_doubt_adm.html.erb
<div id="<%= dom_id doubt %>">
  <h5>Lote <%= link_to doubt.batch.code, show_admin_batch_path(doubt.batch.id)%></h5>
  <h4>
    <% if doubt.visible %>
      <%= turbo_frame_tag "name_ocult_toggle_#{doubt.id}", src: doubts_name_not_ocult_path(doubt.id) %>
    <% else %>
      <%= turbo_frame_tag "name_ocult_toggle_#{doubt.id}", src: doubts_name_ocult_path(doubt.id) %>
    <% end %>
  </h4>
  <p><%= doubt.content %></p>
  <p><%= l(doubt.updated_at.in_time_zone("Brasilia"), format: :bids_format) %></p>
  <% if doubt.visible %>
    <%= turbo_frame_tag "toggle_visibility_button_#{doubt.id}", src: doubts_visible_path(doubt.id) %>
  <% else %>
    <%= turbo_frame_tag "toggle_visibility_button_#{doubt.id}", src: doubts_not_visible_path(doubt.id) %>
  <% end %>

  <% if doubt.answered %>
    <%= turbo_frame_tag "toggle_answered_button_#{doubt.id}", src: answered_button_checked_path(doubt.id) %>
  <% else %>
    <%= turbo_frame_tag "toggle_answered_button_#{doubt.id}", src: answered_button_unchecked_path(doubt.id) %>
  <% end %>
  

  <div data-controller="answers">
    <button data-action="click->answers#toggleSection">Respostas</button>
    <section id="answers_<%= doubt.id %>", data-answers-target="section", class="hidden">
      <%= render doubt.answers %>
      <% if doubt.answers.empty? %>
        <p id="no_answers_<%=doubt.id%>">Ainda não existem respostas para essa dúvida</p>
      <% end %>
    </section>
    <div class="hidden", data-answers-target="new_answer_form">
      <div id="error-messages-answer_<%=doubt.id%>"></div>
      <%= turbo_frame_tag "new_answer_#{doubt.id}", src: new_batch_doubt_answer_path(doubt.batch.id, doubt.id) %>
    </div>
  </div>
</div>

app/views/doubts/_error_message.html.erb
<% if @error_message.present? %>
  <div id="error_answer">
    <%= @error_message %>
  </div>
<% end %>

app/views/doubts/_name_not_ocult.html.erb
<%= turbo_frame_tag "name_ocult_toggle_#{id}", src: doubts_name_not_ocult_path(id) %>

app/views/doubts/_no_doubts.html.erb
<p id="no_doubts">Ainda não existem dúvidas nesse lote</p>

app/views/doubts/_not_visible.html.erb
<%= turbo_frame_tag "toggle_visibility_button_#{id}", src: doubts_not_visible_path(id) %>

app/views/doubts/answered_checked.html.erb
<%= turbo_frame_tag "toggle_answered_button_#{@id}", target: "_top" do %>
   <%= button_to 'Marcar como não respondida', set_doubt_answered_path(@id), id: "button_toggle_answered_#{@id}", method: :patch %>
<% end %>

app/views/doubts/error_page.html.erb
<h3>Nâo foi possível concluir sua solicitação, você deve estar comentendo algum desses erros</h3>
<ul>
  <li>Tentando criar uma dúvida não estando authenticado</li>
  <li>Tentando criar uma dúvida após o leilão ter acabado e não ser o ganhador</li>
  <li>Tentando criar uma dúvida com dados importantes faltantes</li>
  <li>Tentando criar uma dúvida em nome de outro usuário</li>
</ul>

app/views/doubts/name_not_ocult.html.erb
<%= turbo_frame_tag "name_ocult_toggle_#{@doubt.id}", target: "_top" do %>
  <span>
    <%= link_to @doubt.user.name, users_profile_path(@doubt.user.id), data: { turbo_frame: "_top" }%>
    <% if @doubt.user.admin %>
      (Administrador)
    <% end %>
  </span>
<% end %>

app/views/doubts/new.html.erb
<%= turbo_frame_tag "new_doubt", target: "_top" do %>
  <%= form_with(model: [@doubt.batch, @doubt]) do |f| %>
    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
      <%= f.hidden_field :batch_id, value: @doubt.batch.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= f.submit 'Enviar' %>
    </div>
  <% end %>
<% end %>

app/views/doubts/not_answered.html.erb
<%= turbo_stream_from 'not_answered' %>

<h2>Dúvidas não respondidas</h2>
<div id='not_answereds'>
  <%= render partial: 'doubt_adm', collection: @doubts, as: :doubt %>
  <% if @doubts.empty? %>
    <p id="no_doubts_open">Não há dúvidas em aberto</p>
  <% end %>
</div>

app/views/doubts/not_visible.html.erb
<%= turbo_frame_tag "toggle_visibility_button_#{@id}", target: "_top" do %>
   <%= button_to 'Desocultar', set_doubt_visibility_path(@id), id: "button_toggle_visibility_#{@id}", method: :patch %>
<% end %>

app/views/doubts/visible.html.erb
<%= turbo_frame_tag "toggle_visibility_button_#{@id}", target: "_top" do %>
   <%= button_to 'Ocultar', set_doubt_visibility_path(@id), id: "button_toggle_visibility_#{@id}", method: :patch %>
<% end %>