config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :user_favorite_batches, only: [:index]
  resources :items, only: [:new, :create, :index, :destroy, :edit, :update]
  resources :item_categories, only: [:new, :create, :edit, :update]
  resources :batches, only: [:new, :create, :show, :index] do
    get 'search', on: :collection
    get 'admin', on: :member, to: 'batches#show_admin', as: 'show_admin'
    get 'in_progress', on: :collection
    get 'future', on: :collection
    resources :bids, only: [:create, :new]
    resources :doubts, only: [:create, :new] do
      resources :answers, only: [:create, :new]
    end
    get 'expired', on: :collection
    get 'batches_with_my_bids', on: :collection
    patch 'cancel', on: :member
    patch 'close', on: :member
  end
  resources :batch_items, only: [:create]
  patch 'doubts/:id/set_answered', to: 'doubts#set_answered', as: 'set_doubt_answered'
  get 'doubts/not_answered', to: 'doubts#not_answered'
  get 'doubts/:id/checked_answered_adm_button', to: 'doubts#answered_checked', as: 'answered_button_checked'
  get 'doubts/:id/unchecked_answered_adm_button', to: 'doubts#answered_unchecked', as: 'answered_button_unchecked'
  get 'doubts/:id/visible', to: 'doubts#visible', as: 'doubts_visible'
  get 'doubts/:id/not_visible', to: 'doubts#not_visible', as: 'doubts_not_visible'
  get 'doubts/:id/name_not_ocult', to: 'doubts#name_not_ocult', as: 'doubts_name_not_ocult'
  get 'doubts/:id/name_ocult', to: 'doubts#name_ocult', as: 'doubts_name_ocult'
  delete 'user_favorite_batches/delete_favorited/:id', to: 'user_favorite_batches#delete_favorited', as: 'user_favorited_batches_delete_favorited'
  post 'user_favorite_batches/:user_id/:batch_id', to: 'user_favorite_batches#create', as: 'create_user_favorite_batch'
  patch 'doubts/:id/set_visibility', to: 'doubts#set_visiblity', as: 'set_doubt_visibility'
  delete 'batch_items', to: 'batch_items#delete_many'
  patch 'batches/:batch_id/approve/:user_id', to: 'batches#approve', as: 'approve_batch'
  get 'users/block_and_unblock_page', to: 'users#block_and_unblock_page', as: 'block_and_unblock_cpf_page'
  get 'users/:id', to: 'users#profile', as: 'users_profile'
  patch '/users/:id/block_and_unblock_cpf', to: 'users#block_and_unblock', as: 'block_user_cpf'
  patch '/users(/:cpf)/block_and_unblock_cpf_in_page', to: 'users#block_and_unblock_cpf_in_page', as: 'block_user_cpf_in_page'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :doubt
  belongs_to :user
  validates :content, :user_id, :doubt_id, presence: true

  after_create_commit :handle_answering_doubt
  after_create_commit :handle_broadcasting
  


  def handle_answering_doubt
    if user.admin
      doubt.answered = true
      doubt.save!
    else
      doubt.answered = false
      doubt.save!
    end
  end

  def handle_broadcasting
    if doubt.answers.count == 1
      broadcast_remove_to "batch", target: "no_answers_#{doubt.id}"
      broadcast_remove_to "not_answered", target: "no_answers_#{doubt.id}"
      broadcast_remove_to "batch_admin", target: "no_answers_#{doubt.id}"
    end
    broadcast_append_to "batch", target: "answers_#{doubt.id}"
    broadcast_append_to "not_answered", target: "answers_#{doubt.id}"
    broadcast_append_to "batch_admin", target: "answers_#{doubt.id}"
    if user.admin 
      broadcast_replace_to "not_answered", target: "toggle_answered_button_#{doubt.id}", partial: 'doubts/answered_checked', locals: {id: doubt.id}
    else
      broadcast_replace_to "not_answered", target: "toggle_answered_button_#{doubt.id}", partial: 'doubts/answered_unchecked', locals: {id: doubt.id}
    end
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :authenticate_user_with_blocked_cpf!, only: [:create]

  def new
    @doubt = Doubt.find(params[:doubt_id])
    @batch = Batch.find(params[:batch_id])
    @answer = @doubt.answers.new
  end

  def account_suspended

  end

  def create
    @answer = Answer.new(answer_params)

    if current_user.id != @answer.user_id
      respond_to do |format|
        format.turbo_stream
        format.html { render :error_page, status: :unprocessable_entity }
      end
      return
    end

    approved_by = @answer.doubt.batch.approved_by
    start_date = @answer.doubt.batch.start_date
    end_date = @answer.doubt.batch.end_date
    bids_present = @answer.doubt.batch.bids.present?
    maximum_bid_amount = @answer.doubt.batch.bids.maximum(:amount)


    if (approved_by && Date.today < end_date && Date.today >= start_date) ||
       (approved_by && Date.today >= end_date && bids_present && @answer.doubt.batch.bids.find_by(amount: maximum_bid_amount).user_id == current_user.id)
      if @answer.valid?
        @answer.save
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace("error-messages-answer_#{@answer.doubt.id}", partial: "shared/error_messages_answer", locals: { resource: @answer, id: @answer.doubt.id})
          end
          format.html { redirect_to @answer.doubt.batch }
        end
        return
      else
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace("error-messages-answer_#{@answer.doubt.id}", partial: "shared/error_messages_answer", locals: { resource: @answer, id: @answer.doubt.id}) }
          format.html { render :new, status: :unprocessable_entity }
        end
        return
      end
    end

    respond_to do |format|
      format.turbo_stream
      format.html { render :error_page, status: :unprocessable_entity }
    end
  end

  def answer_params
    params.require(:answer).permit(:content, :doubt_id, :user_id)
  end

  def authenticate_user_with_blocked_cpf!
    authenticate_user!

    if current_user.blocked_cpf_id.present?
      redirect_to root_path, alert: 'Sua conta está suspensa'
    end
  end
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer%>">
  <h4><%= link_to answer.user.name, users_profile_path(answer.user.id)%>
    <% if answer.user.admin %>
      (Administrador)
    <% end %>
  </h4>
  <p><%= answer.content %></p>
  <p><%= l(answer.updated_at.in_time_zone("Brasilia"), format: :bids_format) %></p>
</div>

app/views/answers/_notice.html.erb
<%= turbo_frame_tag "notice_answer", target: "_top" do %>
  <%= notice %>
<% end %>

app/views/answers/_tabs.html.erb
<%= link_to 'Respostas', answers_doubt_path(id: id) %>

app/views/answers/error_page.html.erb
<h3>Nâo foi possível concluir sua solicitação, você deve estar comentendo algum desses erros</h3>
<ul>
  <li>Tentando criar uma respota não estando authenticado</li>
  <li>Tentando criar uma respota após o leilão ter acabado e não ser o ganhador</li>
  <li>Tentando criar uma respota com dados importantes faltantes</li>
  <li>Tentando criar uma resposta em nome de outro usuário</li>
</ul>

app/views/answers/new.html.erb
<%= turbo_frame_tag "new_answer_#{@doubt.id}", target: "_top" do %>
  <%= form_with(model: [@doubt.batch, @doubt, @answer],
                data: {controller: 'utilities', action: "turbo:submit-end->utilities#reset"}) do |f| %>
    <div>
      <%= f.label :content, 'Resposta' %>
      <%= f.text_area :content %>
    </div>
      <%= f.hidden_field :doubt_id, value: @answer.doubt.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= f.submit 'Enviar', data: { turbo_frame: "_top" }%>
    </div>
  <% end %>
<% end %>