config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :user_favorite_batches, only: [:index]
  resources :items, only: [:new, :create, :index, :destroy, :edit, :update]
  resources :item_categories, only: [:new, :create, :edit, :update]
  resources :batches, only: [:new, :create, :show, :index] do
    get 'search', on: :collection
    get 'admin', on: :member, to: 'batches#show_admin', as: 'show_admin'
    get 'in_progress', on: :collection
    get 'future', on: :collection
    resources :bids, only: [:create, :new]
    resources :doubts, only: [:create, :new] do
      resources :answers, only: [:create, :new]
    end
    get 'expired', on: :collection
    get 'batches_with_my_bids', on: :collection
    patch 'cancel', on: :member
    patch 'close', on: :member
  end
  resources :batch_items, only: [:create]
  patch 'doubts/:id/set_answered', to: 'doubts#set_answered', as: 'set_doubt_answered'
  get 'doubts/not_answered', to: 'doubts#not_answered'
  get 'doubts/:id/checked_answered_adm_button', to: 'doubts#answered_checked', as: 'answered_button_checked'
  get 'doubts/:id/unchecked_answered_adm_button', to: 'doubts#answered_unchecked', as: 'answered_button_unchecked'
  get 'doubts/:id/visible', to: 'doubts#visible', as: 'doubts_visible'
  get 'doubts/:id/not_visible', to: 'doubts#not_visible', as: 'doubts_not_visible'
  get 'doubts/:id/name_not_ocult', to: 'doubts#name_not_ocult', as: 'doubts_name_not_ocult'
  get 'doubts/:id/name_ocult', to: 'doubts#name_ocult', as: 'doubts_name_ocult'
  delete 'user_favorite_batches/delete_favorited/:id', to: 'user_favorite_batches#delete_favorited', as: 'user_favorited_batches_delete_favorited'
  post 'user_favorite_batches/:user_id/:batch_id', to: 'user_favorite_batches#create', as: 'create_user_favorite_batch'
  patch 'doubts/:id/set_visibility', to: 'doubts#set_visiblity', as: 'set_doubt_visibility'
  delete 'batch_items', to: 'batch_items#delete_many'
  patch 'batches/:batch_id/approve/:user_id', to: 'batches#approve', as: 'approve_batch'
  get 'users/block_and_unblock_page', to: 'users#block_and_unblock_page', as: 'block_and_unblock_cpf_page'
  get 'users/:id', to: 'users#profile', as: 'users_profile'
  patch '/users/:id/block_and_unblock_cpf', to: 'users#block_and_unblock', as: 'block_user_cpf'
  patch '/users(/:cpf)/block_and_unblock_cpf_in_page', to: 'users#block_and_unblock_cpf_in_page', as: 'block_user_cpf_in_page'
end

app/models/user_favorite_batch.rb
class UserFavoriteBatch < ApplicationRecord
  belongs_to :user
  belongs_to :batch
end

app/controllers/user_favorite_batches_controller.rb
class UserFavoriteBatchesController < ApplicationController
  def index
    @user_favorite_batches = current_user.user_favorite_batches
  end

  def create
    favorited = UserFavoriteBatch.new(user_id: params[:user_id], batch_id: params[:batch_id])
    if current_user.id == favorited.user_id
      favorited.save!
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("toggle_favorite_button_#{favorited.batch_id}",
                partial: 'shared/unfavorite_button',
                locals: {id: favorited.id, batch_id: favorited.batch_id})
        end
        format.html { redirect_back(fallback_location: root_path) }
      end
    end 
  end

  def delete_favorited
    favorited = UserFavoriteBatch.find(params[:id])
    if current_user.id == favorited.user_id
      favorited.destroy!
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("toggle_favorite_button_#{favorited.batch_id}",
                partial: 'shared/favorite_button',
                locals: {id: favorited.id, user_id: current_user.id, batch_id: favorited.batch_id})
        end
        format.html { redirect_back(fallback_location: root_path) }
      end
    end
  end

end

app/views/user_favorite_batches/_user_favorite_batch.html.erb
<div>
  <div id="toggle_favorite_button_<%="#{favorited_batch.batch_id}"%>">
    <%= button_to 'Desfavoritar', user_favorited_batches_delete_favorited_path(favorited_batch.id), method: :delete%>
  </div>
  <% if favorited_batch.batch.end_date <= Date.today %>
    <p>O leilão desse lote já acabou</p>
  <% end %>
  <dl>
      <dt>Código</dt>
      <dd><%= link_to favorited_batch.batch.code, batch_path(favorited_batch.batch.id)%></dd>
      <dt>Categoria de itens</dt>
      <dd>
      <% favorited_batch.batch.batch_items.each_with_index do |batch_item, index| %>
        <span><%= batch_item.item.item_category.name %></span>
        <% if index < (favorited_batch.batch.batch_items.length - 1) %>
          ,
        <% end %>
      <% end %>
      </dd>
  </dl>
</div>

app/views/user_favorite_batches/index.html.erb
<h1>Lotes favoritados</h1>

<section>
  <% if @user_favorite_batches.present? %>
    <%= render partial: 'user_favorite_batches/user_favorite_batch', collection: @user_favorite_batches, as: :favorited_batch%>
  <% else %>
    <p>Você ainda não favoritou nenhum lote</p>
  <% end %>
</section>